apiVersion: v1
kind: Service
metadata:
  name: starbucks-cashier-service
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    name: starbucks-cashier